#**Import Library**

In [ ]:
import pandas as pd
import sqlite3
import csv
from ipywidgets import Layout, widgets, Style
from IPython.display import display
from datetime import datetime
import datetime
from datetime import date, timedelta
from IPython.display import display, clear_output

# Download File

In [ ]:
!gdown 1lSyFEYfLmnpUG2nxrASGJwBOpYY3m6hVwW5I0vIQqoo

Downloading...
From (original): https://drive.google.com/uc?id=1lSyFEYfLmnpUG2nxrASGJwBOpYY3m6hVwW5I0vIQqoo
From (redirected): https://docs.google.com/spreadsheets/d/1lSyFEYfLmnpUG2nxrASGJwBOpYY3m6hVwW5I0vIQqoo/export?format=xlsx
To: /content/DUMMY DATABASE.xlsx
29.7kB [00:00, 67.5MB/s]

In [ ]:
read_file = pd.read_excel ("DUMMY DATABASE.xlsx",'BUKU')
read_file1 = pd.read_excel ("DUMMY DATABASE.xlsx","BUKU_COPY")
read_file2 = pd.read_excel ("DUMMY DATABASE.xlsx","ANGGOTA")
read_file3 = pd.read_excel ("DUMMY DATABASE.xlsx","PENJAGA_PERPUSTAKAAN")
read_file4 = pd.read_excel ("DUMMY DATABASE.xlsx","PEMINJAMAN")
read_file5 = pd.read_excel ("DUMMY DATABASE.xlsx","KLASIFIKASI")
read_file6 = pd.read_excel ("DUMMY DATABASE.xlsx","PENERBIT")
read_file7 = pd.read_excel ("DUMMY DATABASE.xlsx","PENGARANG")

# Write the dataframe object
# into csv file
read_file.to_csv ("DUMMY DATABASE BUKU.csv",  index = None,  header=True)
read_file1.to_csv ("DUMMY DATABASE BUKU_COPY.csv",  index = None,  header=True)
read_file2.to_csv ("DUMMY DATABASE ANGGOTA.csv",  index = None,  header=True)
read_file3.to_csv ("DUMMY DATABASE PENJAGA_PERPUSTAKAAN.csv",  index = None,  header=True)
read_file4.to_csv ("DUMMY DATABASE PEMINJAMAN.csv",  index = None,  header=True)
read_file5.to_csv ("DUMMY DATABASE KLASIFIKASI.csv",  index = None,  header=True)
read_file6.to_csv ("DUMMY DATABASE PENERBIT.csv",  index = None,  header=True)
read_file7.to_csv ("DUMMY DATABASE PENGARANG.csv",  index = None,  header=True)

# Pembuatan SQL

In [ ]:
# Buat koneksi ke database SQLite
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()
cursor.execute('''DROP TABLE IF EXISTS buku''')
cursor.execute('''DROP TABLE IF EXISTS buku_per_copy''')
cursor.execute('''DROP TABLE IF EXISTS anggota''')
cursor.execute('''DROP TABLE IF EXISTS penjaga_perpustakaan''')
cursor.execute('''DROP TABLE IF EXISTS peminjaman''')
cursor.execute('''DROP TABLE IF EXISTS klasifikasi''')
cursor.execute('''DROP TABLE IF EXISTS penerbit''')
cursor.execute('''DROP TABLE IF EXISTS pengarang''')

# Buat tabel buku
cursor.execute('''CREATE TABLE buku (
                 ID_Buku TEXT PRIMARY KEY,
                 judul TEXT,
                 pengarang TEXT,
                 penerbit TEXT,
                 Tahun_terbit INTEGER,
                 klasifikasi TEXT,
                 FOREIGN KEY (pengarang) REFERENCES pengarang(id_pengarang),
                 FOREIGN KEY (penerbit) REFERENCES penerbit(id_penerbit),
                 FOREIGN KEY (klasifikasi) REFERENCES klasifikasi(id_klasifikasi)
                 )''')

# Buat tabel bukucopy
cursor.execute('''CREATE TABLE buku_per_copy (
                 id_buku_per_copy TEXT PRIMARY KEY,
                 Id_buku TEXT,
                 tersedia INTEGER,
                 FOREIGN KEY (Id_buku) REFERENCES buku(ID_Buku)
                 )''')

# Buat tabel anggota
cursor.execute('''CREATE TABLE anggota (
                 id_anggota TEXT PRIMARY KEY,
                 nama_anggota TEXT,
                 nik TEXT,
                 ttl TEXT,
                 alamat TEXT,
                 nomor_telepon TEXT)''')

# Buat tabel penjaga perpustakaan
cursor.execute('''CREATE TABLE penjaga_perpustakaan (
                 id_penjaga TEXT PRIMARY KEY,
                 nama_penjaga TEXT,
                 jadwal_kerja TEXT,
                 jam_kerja TEXT)''')

# Buat tabel peminjaman
cursor.execute('''CREATE TABLE peminjaman (
                 id_peminjaman TEXT PRIMARY KEY,
                 id_buku_per_copy TEXT,
                 id_anggota TEXT,
                 id_penjaga TEXT,
                 tanggal_peminjaman TEXT,
                 tenggat_pengembalian TEXT,
                 tanggal_pengembalian TEXT,
                 denda REAL,
                 FOREIGN KEY (id_buku_per_copy) REFERENCES buku_per_copy(id_buku_per_copy)
                 FOREIGN KEY (id_anggota) REFERENCES anggota(id_anggota)
                 FOREIGN KEY (id_penjaga) REFERENCES penjaga_perpustakaan(id_penjaga)
                 )''')

# Buat tabel klasifikasi
cursor.execute('''CREATE TABLE klasifikasi (
                 id_klasifikasi TEXT PRIMARY KEY,
                 klasifikasi TEXT
                 )''')

# Buat tabel pengarang
cursor.execute('''CREATE TABLE pengarang (
                 id_pengarang TEXT PRIMARY KEY,
                 nama_pengarang TEXT,
                 email_pengarang TEXT,
                 tempat_tinggal TEXT)''')

# Buat tabel penerbit
cursor.execute('''CREATE TABLE penerbit (
                 id_penerbit TEXT PRIMARY KEY,
                 nama_penerbit TEXT,
                 telepon INTEGER,
                 email_penerbit TEXT)''')


# Buka file CSV buku
with open('DUMMY DATABASE BUKU.csv', 'r') as berkas_csv:
    data_csv = csv.reader(berkas_csv, delimiter=',')
    next(data_csv)  # Skip header row
    data = list(data_csv)
    for row in data:
        cursor.execute("INSERT INTO buku (ID_Buku, judul, pengarang, penerbit, Tahun_terbit, klasifikasi) VALUES (?, ?, ?, ?, ?, ?)", tuple(row))

# Buka file CSV anggota
with open('DUMMY DATABASE ANGGOTA.csv', 'r') as berkas_csv:
    data_csv = csv.reader(berkas_csv, delimiter=',')
    next(data_csv)  # Skip header row
    data = list(data_csv)
    for row in data:
        if len(row) == 6:  # Check if the row has 6 values
            cursor.execute("INSERT INTO anggota (id_anggota, nama_anggota, nik, ttl, alamat, nomor_telepon) VALUES (?, ?, ?, ?, ?, ?)", row)
        else:
            print(f"Skipping row: {row} (incorrect number of values)")

# Buka file CSV penjaga perpustakaan
with open('DUMMY DATABASE PENJAGA_PERPUSTAKAAN.csv', 'r') as berkas_csv:
    data_csv = csv.reader(berkas_csv, delimiter=',')
    next(data_csv)  # Skip header row
    data = list(data_csv)
    for row in data:
        if len(row) == 4:  # Check if the row has 7 values
            cursor.execute("INSERT INTO penjaga_perpustakaan (id_penjaga, nama_penjaga, jadwal_kerja, jam_kerja) VALUES (?, ?, ?, ?)", (row))
        else:
            print(f"Skipping row: {row} (incorrect number of values)")

# Buka file CSV buku copy
with open('DUMMY DATABASE BUKU_COPY.csv', 'r') as berkas_csv:
    data_csv = csv.reader(berkas_csv, delimiter=',')
    next(data_csv)  # Skip header row
    data = list(data_csv)
    for row in data:
        if len(row) == 3:  # Check if the row has 7 values
            cursor.execute("INSERT INTO buku_per_copy (id_buku_per_copy, id_buku, tersedia) VALUES (?, ?, ?)", (row))
        else:
            print(f"Skipping row: {row} (incorrect number of values)")

# Buka file CSV peminjaman
with open('DUMMY DATABASE PEMINJAMAN.csv', 'r') as berkas_csv:
    data_csv = csv.reader(berkas_csv, delimiter=',')
    next(data_csv)  # Skip header row
    data = list(data_csv)
    for row in data:
        if len(row) == 8:  # Check if the row has 7 values
            cursor.execute("INSERT INTO peminjaman (id_peminjaman, id_buku_per_copy, id_anggota, id_penjaga, tanggal_peminjaman, tenggat_pengembalian, tanggal_pengembalian, denda) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", (row))
        else:
            print(f"Skipping row: {row} (incorrect number of values)")

# Buka file CSV klasifikasi
with open('DUMMY DATABASE KLASIFIKASI.csv', 'r') as berkas_csv:
    data_csv = csv.reader(berkas_csv, delimiter=',')
    next(data_csv)  # Skip header row
    data = list(data_csv)
    for row in data:
        if len(row) == 2:  # Check if the row has 7 values
            cursor.execute("INSERT INTO klasifikasi (id_klasifikasi, klasifikasi) VALUES (?, ?)", (row))
        else:
            print(f"Skipping row: {row} (incorrect number of values)")

# Buka file CSV pengarang
with open('DUMMY DATABASE PENGARANG.csv', 'r') as berkas_csv:
    data_csv = csv.reader(berkas_csv, delimiter=',')
    next(data_csv)  # Skip header row
    data = list(data_csv)
    for row in data:
        if len(row) == 4:  # Check if the row has 7 values
            cursor.execute("INSERT INTO pengarang (id_pengarang, nama_pengarang, email_pengarang, tempat_tinggal) VALUES (?, ?, ?, ?)", (row))
        else:
            print(f"Skipping row: {row} (incorrect number of values)")

# Buka file CSV penerbit
with open('DUMMY DATABASE PENERBIT.csv', 'r') as berkas_csv:
    data_csv = csv.reader(berkas_csv, delimiter=',')
    next(data_csv)  # Skip header row
    data = list(data_csv)
    for row in data:
        if len(row) == 4:  # Check if the row has 7 values
            cursor.execute("INSERT INTO penerbit (id_penerbit, nama_penerbit, telepon, email_penerbit) VALUES (?, ?, ?, ?)", (row))
        else:
            print(f"Skipping row: {row} (incorrect number of values)")

# Simpan perubahan ke database
conn.commit()

# Tutup koneksi ke database
conn.close()

In [ ]:
# Koneksi ke database
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()

cursor.execute("SELECT COUNT(id_anggota) FROM anggota")
counter_anggota=cursor.fetchone()[0]

cursor.execute("SELECT COUNT(id_buku) FROM buku")
counter_buku=cursor.fetchone()[0]

cursor.execute("SELECT COUNT(id_buku_per_copy) FROM buku_per_copy")
counter_bukucopy=cursor.fetchone()[0]

cursor.execute("SELECT COUNT(id_pengarang) FROM pengarang")
counter_pengarang=cursor.fetchone()[0]

cursor.execute("SELECT COUNT(id_penerbit) FROM penerbit")
counter_penerbit=cursor.fetchone()[0]

cursor.execute("SELECT COUNT(id_klasifikasi) FROM klasifikasi")
counter_klasifikasi=cursor.fetchone()[0]

cursor.execute("SELECT COUNT(id_peminjaman) FROM peminjaman")
counter_peminjaman=cursor.fetchone()[0]

# POV Penjaga

## Tabel Peminjaman

### Melihat tabel

In [ ]:
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM peminjaman;")
data1 = cursor.fetchall()
cursor.execute(f"PRAGMA table_info(peminjaman);")
data102 = cursor.fetchall()
data102 = [item[1] for item in data102]

df = pd.DataFrame(data1, columns=data102)
df

,id_peminjaman,id_buku_per_copy,id_anggota,id_penjaga,tanggal_peminjaman,tenggat_pengembalian,tanggal_pengembalian,denda
0,PIJ1,BK37,AG5,P1,2024-01-22,2024-02-05,2024-02-01,0.0
1,PIJ2,BK22,AG5,P3,2024-01-22,2024-02-05,2024-02-06,5000.0
2,PIJ3,BK8,AG1,P3,2024-01-22,2024-02-05,2024-01-31,0.0
3,PIJ4,BK39,AG3,P1,2024-01-22,2024-02-05,2024-02-04,0.0
4,PIJ5,BK40,AG5,P1,2024-01-22,2024-02-05,2024-02-03,0.0
5,PIJ6,BK35,AG4,P2,2024-01-23,2024-02-06,2024-02-04,0.0
6,PIJ7,BK19,AG2,P2,2024-01-23,2024-02-06,2024-01-31,0.0
7,PIJ8,BK25,AG1,P2,2024-01-23,2024-02-06,2024-02-07,5000.0
8,PIJ9,BK9,AG3,P2,2024-01-23,2024-02-06,2024-02-04,0.0
9,PIJ10,BK5,AG3,P2,2024-01-23,2024-02-06,2024-02-08,10000.0
10,PIJ11,BK20,AG5,P2,2024-01-23,2024-02-06,2024-02-03,0.0
11,PIJ12,BK53,AG2,P4,2024-01-24,2024-02-07,2024-02-03,0.0
12,PIJ13,BK24,AG4,P4,2024-01-24,2024-02-07,2024-02-07,0.0
13,PIJ14,BK46,AG3,P2,2024-01-25,2024-02-08,2024-02-03,0.0
14,PIJ15,BK52,AG4,P2,2024-01-25,2024-02-08,2024-02-05,0.0
15,PIJ16,BK51,AG1,P2,2024-01-25,2024-02-08,2024-02-03,0.0
16,PIJ17,BK27,AG2,P2,2024-01-25,2024-02-08,2024-02-07,0.0
17,PIJ18,BK16,AG2,P2,2024-01-25,2024-02-08,2024-01-31,0.0
18,PIJ19,BK18,AG2,P1,2024-01-26,2024-02-09,2024-02-07,0.0
19,PIJ20,BK43,AG2,P1,2024-01-26,2024-02-09,2024-02-03,0.0

### Input Peminjaman

In [ ]:
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()
cursor.execute("SELECT DISTINCT id_anggota FROM anggota;")
data1 = cursor.fetchall()

cursor.execute("SELECT DISTINCT id_buku_per_copy FROM buku_per_copy;")
data2 = cursor.fetchall()

cursor.execute("SELECT DISTINCT id_penjaga FROM penjaga_perpustakaan;")
data3 = cursor.fetchall()


listanggota = [item[0] for item in data1]
listidbuku = [item[0] for item in data2]
listpenjaga = [item[0] for item in data3]

# Membuat widget input
id_anggota_input =widgets.Dropdown(
    options=listanggota,
    value=listanggota[0],
    description='Id_anggota:',
    disabled=False,)

id_buku_input = widgets.Dropdown(
    options=listidbuku,
    value=listidbuku[0],
    description='ID_buku_percopy:',
    disabled=False,)

id_penjaga_input = widgets.Dropdown(
    options=listpenjaga,
    value=listpenjaga[0],
    description='Id_Penjaga:',
    disabled=False,)

tanggal_pinjam_input = widgets.DatePicker(
    description='Tgl Pinjam:',
    disabled=False,
    value=datetime.date.today())

submit_button = widgets.Button(
    description='Masukkan Data',
    disabled=False,
    button_style='success',
    tooltip='Klik untuk memasukkan data peminjaman')

availability_output = widgets.Text(
    value='',
    description='Availability:',
    disabled=True)

def ketersediaan_buku(change):
    with sqlite3.connect('perpustakaan.db') as conn:
        c = conn.cursor()
        try:
            c.execute("SELECT tersedia FROM buku_per_copy WHERE id_buku_per_copy = ?", (id_buku_input.value,))
            result = c.fetchone()
            if result:
                tersedia = result[0]
                availability_output.value = "Tersedia" if tersedia == 1 else "Tidak Tersedia"
            else:
                availability_output.value = "ID Buku tidak ditemukan"
        except Exception as e:
            print("Terjadi kesalahan: ", e)

id_buku_input.observe(ketersediaan_buku, names='value')

#####
# Function to update the tersedia column in the buku_per_copy table
def update_tersedia_value(id_buku):
    # Connect to the SQLite database
    connection = sqlite3.connect('perpustakaan.db')
    cursor = connection.cursor()

    # Execute the SQL UPDATE statement to update the tersedia column
    cursor.execute("UPDATE buku_per_copy SET tersedia = ? WHERE id_buku_per_copy = ?;", (0,id_buku_input.value,))

    # Commit the changes and close the connection
    connection.commit()
    connection.close()

# Example: call the update_tersedia_value function when the id_buku_input widget's value changes

def generate_next_id():
    global counter_peminjaman
    counter_peminjaman +=1

    # Menghasilkan ID dengan format "KLS" diikuti dengan nomor
    next_id_with_format = f"PIJ{counter_peminjaman}"

    return next_id_with_format



def insert_data(b):
    with sqlite3.connect('perpustakaan.db') as conn:
        c = conn.cursor()
        # Mengaktifkan foreign key
        c.execute('PRAGMA foreign_keys = ON')
        try:
            new_id = generate_next_id()
            c.execute('''INSERT INTO peminjaman (id_peminjaman,id_buku_per_copy, id_anggota, id_penjaga, tanggal_peminjaman, tenggat_pengembalian, tanggal_pengembalian, denda) VALUES (?,?, ?, ?, ?, ?, NULL, NULL)''',
                      (new_id, id_buku_input.value, id_anggota_input.value, id_penjaga_input.value, str(tanggal_pinjam_input.value), str(tanggal_pinjam_input.value+timedelta(14))))
            print("Data peminjaman berhasil dimasukkan.")
            last_row_id = c.lastrowid
            # Fetch the last inserted row using the row ID
            c.execute("SELECT * FROM peminjaman WHERE ROWID = ?;", (last_row_id,))
            last_row = c.fetchone()
            print(last_row)
        except sqlite3.IntegrityError as e:
            print("Gagal memasukkan data: ", e)
        except Exception as e:
            print("Terjadi kesalahan: ", e)



submit_button.on_click(insert_data)
submit_button.on_click(update_tersedia_value)

display(id_anggota_input, id_buku_input, id_penjaga_input,availability_output, tanggal_pinjam_input, submit_button)

Dropdown(description='Id_anggota:', options=('AG1', 'AG2', 'AG3', 'AG4', 'AG5'), value='AG1')

Dropdown(description='ID_buku_percopy:', options=('BK1', 'BK10', 'BK11', 'BK12', 'BK13', 'BK14', 'BK15', 'BK16…

Dropdown(description='Id_Penjaga:', options=('P1', 'P2', 'P3', 'P4'), value='P1')

Text(value='', description='Availability:', disabled=True)

DatePicker(value=datetime.date(2024, 6, 6), description='Tgl Pinjam:')

Button(button_style='success', description='Masukkan Data', style=ButtonStyle(), tooltip='Klik untuk memasukka…

Data peminjaman berhasil dimasukkan.
('PIJ21', 'BK1', 'AG1', 'P1', '2024-06-06', '2024-06-20', None, None)

Lihat Tabel Peminjaman

In [ ]:
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM peminjaman;")
data1 = cursor.fetchall()
cursor.execute(f"PRAGMA table_info(peminjaman);")
data102 = cursor.fetchall()
data102 = [item[1] for item in data102]

df = pd.DataFrame(data1, columns=data102)
df

,id_peminjaman,id_buku_per_copy,id_anggota,id_penjaga,tanggal_peminjaman,tenggat_pengembalian,tanggal_pengembalian,denda
0,PIJ1,BK37,AG5,P1,2024-01-22,2024-02-05,2024-02-01,0.0
1,PIJ2,BK22,AG5,P3,2024-01-22,2024-02-05,2024-02-06,5000.0
2,PIJ3,BK8,AG1,P3,2024-01-22,2024-02-05,2024-01-31,0.0
3,PIJ4,BK39,AG3,P1,2024-01-22,2024-02-05,2024-02-04,0.0
4,PIJ5,BK40,AG5,P1,2024-01-22,2024-02-05,2024-02-03,0.0
5,PIJ6,BK35,AG4,P2,2024-01-23,2024-02-06,2024-02-04,0.0
6,PIJ7,BK19,AG2,P2,2024-01-23,2024-02-06,2024-01-31,0.0
7,PIJ8,BK25,AG1,P2,2024-01-23,2024-02-06,2024-02-07,5000.0
8,PIJ9,BK9,AG3,P2,2024-01-23,2024-02-06,2024-02-04,0.0
9,PIJ10,BK5,AG3,P2,2024-01-23,2024-02-06,2024-02-08,10000.0
10,PIJ11,BK20,AG5,P2,2024-01-23,2024-02-06,2024-02-03,0.0
11,PIJ12,BK53,AG2,P4,2024-01-24,2024-02-07,2024-02-03,0.0
12,PIJ13,BK24,AG4,P4,2024-01-24,2024-02-07,2024-02-07,0.0
13,PIJ14,BK46,AG3,P2,2024-01-25,2024-02-08,2024-02-03,0.0
14,PIJ15,BK52,AG4,P2,2024-01-25,2024-02-08,2024-02-05,0.0
15,PIJ16,BK51,AG1,P2,2024-01-25,2024-02-08,2024-02-03,0.0
16,PIJ17,BK27,AG2,P2,2024-01-25,2024-02-08,2024-02-07,0.0
17,PIJ18,BK16,AG2,P2,2024-01-25,2024-02-08,2024-01-31,0.0
18,PIJ19,BK18,AG2,P1,2024-01-26,2024-02-09,2024-02-07,0.0
19,PIJ20,BK43,AG2,P1,2024-01-26,2024-02-09,2024-02-03,0.0
20,PIJ21,BK1,AG1,P1,2024-06-06,2024-06-20,None,NaN

lihat tabel buku percopy

In [ ]:
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM buku_per_copy;")
data1 = cursor.fetchall()
cursor.execute(f"PRAGMA table_info(buku_per_copy);")
data102 = cursor.fetchall()
data102 = [item[1] for item in data102]

df = pd.DataFrame(data1, columns=data102)
df

   id_buku_per_copy Id_buku  tersedia
0               BK1      B9         0
1               BK2      B9         1
2               BK3      B7         1
3               BK4      B8         1
4               BK5      B3         1
5               BK6      B6         1
6               BK7      B7         1
7               BK8      B2         1
8               BK9      B6         1
9              BK10      B8         1
10             BK11      B1         1
11             BK12      B8         1
12             BK13      B2         1
13             BK14      B8         1
14             BK15      B1         1
15             BK16     B10         1
16             BK17      B9         1
17             BK18      B9         1
18             BK19      B6         1
19             BK20      B9         1
20             BK21      B1         1
21             BK22      B5         1
22             BK23      B8         1
23             BK24      B8         1
24             BK25      B4         1
25             BK26      B1         1
26             BK27      B7         1
27             BK28      B8         1
28             BK29      B2         1
29             BK30      B3         1
30             BK31      B8         1
31             BK32      B2         1
32             BK33      B9         1
33             BK34      B8         1
34             BK35      B5         1
35             BK36      B3         1
36             BK37      B6         1
37             BK38      B1         1
38             BK39      B5         1
39             BK40      B9         1
40             BK41      B1         1
41             BK42      B5         1
42             BK43      B8         1
43             BK44      B3         1
44             BK45      B6         1
45             BK46      B9         1
46             BK47      B3         1
47             BK48      B4         1
48             BK49      B6         1
49             BK50      B5         1
50             BK51      B9         1
51             BK52      B7         1
52             BK53      B3         1

### Input Pengembalian

In [ ]:
from ipywidgets import Layout, widgets, Style
from IPython.display import display
from datetime import datetime, timedelta

# Membuat widget input
id_peminjaman_input = widgets.Text(
    value='',
    description='ID Peminjaman:',
    disabled=False)

id_anggota_output = widgets.Text(
    value='',
    description='ID Anggota:',
    disabled=True)

id_buku_output = widgets.Text(
    value='',
    description='ID Buku:',
    disabled=True)

tanggal_kembali_input = widgets.DatePicker(
    description='Tanggal Pengembalian:',
    disabled=False,
    value=datetime.now().date())

submit_button = widgets.Button(
    description='Masukkan Data',
    disabled=False,
    button_style='success',
    tooltip='Klik untuk memasukkan data pengembalian')

def fetch_peminjaman_data(change):
    with sqlite3.connect('perpustakaan.db') as conn:
        c = conn.cursor()
        try:
            c.execute("SELECT id_anggota, id_buku_per_copy FROM peminjaman WHERE id_peminjaman = ?", (id_peminjaman_input.value,))
            result = c.fetchone()
            if result:
                id_anggota, id_buku = result
                id_anggota_output.value = id_anggota
                id_buku_output.value = id_buku
            else:
                id_anggota_output.value = ''
                id_buku_output.value = ''
        except Exception as e:
            print("Terjadi kesalahan: ", e)

id_peminjaman_input.observe(fetch_peminjaman_data, names='value')




def update_tersedia_value(id_buku):
    # Connect to the SQLite database
    connection = sqlite3.connect('perpustakaan.db')
    cursor = connection.cursor()

    # Execute the SQL UPDATE statement to update the tersedia column
    cursor.execute("UPDATE buku_per_copy SET tersedia = ? WHERE id_buku_per_copy = ?;", (1,id_buku_output.value,))

    # Commit the changes and close the connection
    connection.commit()
    connection.close()


def insert_data(b):
    with sqlite3.connect('perpustakaan.db') as conn:
        c = conn.cursor()
        c.execute('PRAGMA foreign_keys = ON')
        try:
            # Mendapatkan data peminjaman berdasarkan id_peminjaman
            c.execute("SELECT tanggal_peminjaman, tenggat_pengembalian FROM peminjaman WHERE id_peminjaman = ?", (id_peminjaman_input.value,))
            result = c.fetchone()
            if result:
                tanggal_peminjaman, tenggat_pengembalian = result
                tanggal_kembali = tanggal_kembali_input.value

                # Menghitung denda
                if tanggal_kembali > datetime.strptime(tenggat_pengembalian, '%Y-%m-%d').date():
                    denda = (tanggal_kembali - datetime.strptime(tenggat_pengembalian, '%Y-%m-%d').date()).days * 5000
                else:
                    denda = 0

                # Memperbarui data peminjaman dengan tanggal_pengembalian dan denda
                c.execute("UPDATE peminjaman SET tanggal_pengembalian = ?, denda = ? WHERE id_peminjaman = ?",
                          (str(tanggal_kembali), denda, id_peminjaman_input.value))
                conn.commit()
                print(f"Data pengembalian berhasil dimasukkan. Denda: Rp{denda}")
            else:
                print("Tidak ada data peminjaman yang ditemukan.")
        except Exception as e:
            print("Terjadi kesalahan: ", e)

submit_button.on_click(insert_data)
submit_button.on_click(update_tersedia_value)
display(id_peminjaman_input, id_anggota_output, id_buku_output, tanggal_kembali_input, submit_button)

Text(value='', description='ID Peminjaman:')

Text(value='', description='ID Anggota:', disabled=True)

Text(value='', description='ID Buku:', disabled=True)

DatePicker(value=datetime.date(2024, 6, 6), description='Tanggal Pengembalian:')

Button(button_style='success', description='Masukkan Data', style=ButtonStyle(), tooltip='Klik untuk memasukka…

Data pengembalian berhasil dimasukkan. Denda: Rp10000

lihat table Peminjaman

In [ ]:
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM peminjaman;")
data1 = cursor.fetchall()
cursor.execute(f"PRAGMA table_info(peminjaman);")
data102 = cursor.fetchall()
data102 = [item[1] for item in data102]

df = pd.DataFrame(data1, columns=data102)
df

,id_peminjaman,id_buku_per_copy,id_anggota,id_penjaga,tanggal_peminjaman,tenggat_pengembalian,tanggal_pengembalian,denda
0,PIJ1,BK37,AG5,P1,2024-01-22,2024-02-05,2024-02-01,0.0
1,PIJ2,BK22,AG5,P3,2024-01-22,2024-02-05,2024-02-06,5000.0
2,PIJ3,BK8,AG1,P3,2024-01-22,2024-02-05,2024-01-31,0.0
3,PIJ4,BK39,AG3,P1,2024-01-22,2024-02-05,2024-02-04,0.0
4,PIJ5,BK40,AG5,P1,2024-01-22,2024-02-05,2024-02-03,0.0
5,PIJ6,BK35,AG4,P2,2024-01-23,2024-02-06,2024-02-04,0.0
6,PIJ7,BK19,AG2,P2,2024-01-23,2024-02-06,2024-01-31,0.0
7,PIJ8,BK25,AG1,P2,2024-01-23,2024-02-06,2024-02-07,5000.0
8,PIJ9,BK9,AG3,P2,2024-01-23,2024-02-06,2024-02-04,0.0
9,PIJ10,BK5,AG3,P2,2024-01-23,2024-02-06,2024-02-08,10000.0
10,PIJ11,BK20,AG5,P2,2024-01-23,2024-02-06,2024-02-03,0.0
11,PIJ12,BK53,AG2,P4,2024-01-24,2024-02-07,2024-02-03,0.0
12,PIJ13,BK24,AG4,P4,2024-01-24,2024-02-07,2024-02-07,0.0
13,PIJ14,BK46,AG3,P2,2024-01-25,2024-02-08,2024-02-03,0.0
14,PIJ15,BK52,AG4,P2,2024-01-25,2024-02-08,2024-02-05,0.0
15,PIJ16,BK51,AG1,P2,2024-01-25,2024-02-08,2024-02-03,0.0
16,PIJ17,BK27,AG2,P2,2024-01-25,2024-02-08,2024-02-07,0.0
17,PIJ18,BK16,AG2,P2,2024-01-25,2024-02-08,2024-01-31,0.0
18,PIJ19,BK18,AG2,P1,2024-01-26,2024-02-09,2024-02-07,0.0
19,PIJ20,BK43,AG2,P1,2024-01-26,2024-02-09,2024-02-03,0.0
20,PIJ21,BK1,AG1,P1,2024-06-06,2024-06-20,2024-06-22,10000.0

lihat table Buku per copy

In [ ]:
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM buku_per_copy;")
data1 = cursor.fetchall()
cursor.execute(f"PRAGMA table_info(buku_per_copy);")
data102 = cursor.fetchall()
data102 = [item[1] for item in data102]

df = pd.DataFrame(data1, columns=data102)
df

   id_buku_per_copy Id_buku  tersedia
0               BK1      B9         1
1               BK2      B9         1
2               BK3      B7         1
3               BK4      B8         1
4               BK5      B3         1
5               BK6      B6         1
6               BK7      B7         1
7               BK8      B2         1
8               BK9      B6         1
9              BK10      B8         1
10             BK11      B1         1
11             BK12      B8         1
12             BK13      B2         1
13             BK14      B8         1
14             BK15      B1         1
15             BK16     B10         1
16             BK17      B9         1
17             BK18      B9         1
18             BK19      B6         1
19             BK20      B9         1
20             BK21      B1         1
21             BK22      B5         1
22             BK23      B8         1
23             BK24      B8         1
24             BK25      B4         1
25             BK26      B1         1
26             BK27      B7         1
27             BK28      B8         1
28             BK29      B2         1
29             BK30      B3         1
30             BK31      B8         1
31             BK32      B2         1
32             BK33      B9         1
33             BK34      B8         1
34             BK35      B5         1
35             BK36      B3         1
36             BK37      B6         1
37             BK38      B1         1
38             BK39      B5         1
39             BK40      B9         1
40             BK41      B1         1
41             BK42      B5         1
42             BK43      B8         1
43             BK44      B3         1
44             BK45      B6         1
45             BK46      B9         1
46             BK47      B3         1
47             BK48      B4         1
48             BK49      B6         1
49             BK50      B5         1
50             BK51      B9         1
51             BK52      B7         1
52             BK53      B3         1

### **Delete Record Peminjaman**
- tujuan : in case petugas ada salah input

In [ ]:
# Function to fetch IDs from the SQL table
def get_ids_from_db():
    connection = sqlite3.connect('perpustakaan.db')  # Replace with your database file
    cursor = connection.cursor()

    cursor.execute("SELECT id_peminjaman FROM peminjaman;")  # Replace 'id' and 'your_table' with actual column and table names
    ids = cursor.fetchall()

    cursor.close()
    connection.close()

    return [str(id[0]) for id in ids]

# Create a dropdown widget to select an ID
id_dropdown = widgets.Dropdown(
    options=get_ids_from_db(),
    description='ID Peminjaman (yang salah) :',
    disabled=False
)

# Create a button to delete the selected record
delete_button = widgets.Button(
    description='Hapus ID_Peminjaman',
    disabled=False,
    button_style='danger',  # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Click to delete',
    icon='trash'
)

# Function to handle the deletion
def delete_record(button):
    id_to_delete = id_dropdown.value
    if id_to_delete:
        connection = sqlite3.connect('perpustakaan.db')  # Replace with your database file
        cursor = connection.cursor()

        cursor.execute("DELETE FROM peminjaman WHERE id_peminjaman = ?;", (id_to_delete,))  # Replace 'id' and 'your_table' with actual column and table names
        connection.commit()

        cursor.close()
        connection.close()

        # Update dropdown options
        id_dropdown.options = get_ids_from_db()
        print(f"Record with ID {id_to_delete} deleted successfully.")

# Display the widgets
display(id_dropdown, delete_button)

# Attach the event handler to the button
delete_button.on_click(delete_record)

Dropdown(description='ID Peminjaman (yang salah) :', options=('PIJ1', 'PIJ10', 'PIJ11', 'PIJ12', 'PIJ13', 'PIJ…

Button(button_style='danger', description='Hapus ID_Peminjaman', icon='trash', style=ButtonStyle(), tooltip='C…

Record with ID PIJ7 deleted successfully.

lihat tabel peminjaman

In [ ]:
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM peminjaman;")
data1 = cursor.fetchall()
cursor.execute(f"PRAGMA table_info(peminjaman);")
data102 = cursor.fetchall()
data102 = [item[1] for item in data102]

df = pd.DataFrame(data1, columns=data102)
df

,id_peminjaman,id_buku_per_copy,id_anggota,id_penjaga,tanggal_peminjaman,tenggat_pengembalian,tanggal_pengembalian,denda
0,PIJ1,BK37,AG5,P1,2024-01-22,2024-02-05,2024-02-01,0.0
1,PIJ2,BK22,AG5,P3,2024-01-22,2024-02-05,2024-02-06,5000.0
2,PIJ3,BK8,AG1,P3,2024-01-22,2024-02-05,2024-01-31,0.0
3,PIJ4,BK39,AG3,P1,2024-01-22,2024-02-05,2024-02-04,0.0
4,PIJ5,BK40,AG5,P1,2024-01-22,2024-02-05,2024-02-03,0.0
5,PIJ6,BK35,AG4,P2,2024-01-23,2024-02-06,2024-02-04,0.0
6,PIJ8,BK25,AG1,P2,2024-01-23,2024-02-06,2024-02-07,5000.0
7,PIJ9,BK9,AG3,P2,2024-01-23,2024-02-06,2024-02-04,0.0
8,PIJ10,BK5,AG3,P2,2024-01-23,2024-02-06,2024-02-08,10000.0
9,PIJ11,BK20,AG5,P2,2024-01-23,2024-02-06,2024-02-03,0.0
10,PIJ12,BK53,AG2,P4,2024-01-24,2024-02-07,2024-02-03,0.0
11,PIJ13,BK24,AG4,P4,2024-01-24,2024-02-07,2024-02-07,0.0
12,PIJ14,BK46,AG3,P2,2024-01-25,2024-02-08,2024-02-03,0.0
13,PIJ15,BK52,AG4,P2,2024-01-25,2024-02-08,2024-02-05,0.0
14,PIJ16,BK51,AG1,P2,2024-01-25,2024-02-08,2024-02-03,0.0
15,PIJ17,BK27,AG2,P2,2024-01-25,2024-02-08,2024-02-07,0.0
16,PIJ18,BK16,AG2,P2,2024-01-25,2024-02-08,2024-01-31,0.0
17,PIJ19,BK18,AG2,P1,2024-01-26,2024-02-09,2024-02-07,0.0
18,PIJ20,BK43,AG2,P1,2024-01-26,2024-02-09,2024-02-03,0.0
19,PIJ21,BK1,AG1,P1,2024-06-06,2024-06-20,2024-06-22,10000.0

## Tabel Anggota

### Melihat Tabel

In [ ]:
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM anggota;")
data1 = cursor.fetchall()
cursor.execute(f"PRAGMA table_info(anggota);")
data102 = cursor.fetchall()
data102 = [item[1] for item in data102]

df = pd.DataFrame(data1, columns=data102)
df

,id_anggota,nama_anggota,nik,ttl,alamat,nomor_telepon
0,AG1,John Smith,3201102201234567,15/04/1990,"Jl. Merdeka No. 123, Jakarta",81234567890
1,AG2,Alice Nurdin Warda,3202103201234568,21/09/1985,"Jl. Kebon Jeruk No. 45, Jakarta",81345678901
2,AG3,Brian Wong,3203104201234569,22/07/1999,"Jl. Melati No. 78, Jakarta",81456789012
3,AG4,Maria Simanjuntak,3204105201234571,19/02/2015,"Jl. Diponegoro No. 89, Jakarta",81567890123
4,AG5,Dimas Pratama Wijaya,3205106201234571,18/03/1995,"Jl. Ahmad Yani No. 101, Jakarta",81678901234
5,ANGOT6,Shinn,2333222,2024-06-07,depok,89566788890
6,AG8,bbb,7878777,2024-06-07,guci,67876544567

### Input/Update Anggota

In [ ]:
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()
cursor.execute("SELECT DISTINCT id_anggota FROM anggota;")
data1 = cursor.fetchall()

# Membuat widget input untuk data anggota

nama_anggota_input = widgets.Text(
    value='',
    description='Nama Anggota:',
    disabled=False)

nik_input = widgets.IntText(
    description='NIK:',
    disabled=False)

ttl_input = widgets.DatePicker(
    description='TTL:',
    disabled=False)

alamat_input = widgets.Text(
    value='',
    description='Alamat:',
    disabled=False)

nomor_telepon_input = widgets.IntText(
    description='No Telepon:',
    disabled=False)

submit_button = widgets.Button(
    description='Masukkan Data',
    disabled=False,
    button_style='success',
    tooltip='Klik untuk memasukkan data peminjaman')


def generate_next_id():
    global counter_anggota
    counter_anggota +=1

    # Menghasilkan ID dengan format "KLS" diikuti dengan nomor
    next_id_with_format = f"AG{counter_anggota}"

    return next_id_with_format


def insert_data(b):
    with sqlite3.connect('perpustakaan.db') as conn:
        c = conn.cursor()
        c.execute('PRAGMA foreign_keys = ON')
        try:
            # Memasukkan data anggota
            nextid = generate_next_id()
            c.execute('''
                INSERT INTO anggota (id_anggota, nama_anggota, nik, ttl, alamat, nomor_telepon)
                VALUES (?, ?, ?, ?, ?, ?)
                ''',
                (nextid ,
                nama_anggota_input.value,
                nik_input.value,
                ttl_input.value,
                alamat_input.value,
                nomor_telepon_input.value))
            print("Data anggota berhasil dimasukkan.")
        except sqlite3.IntegrityError as e:
            print("Gagal memasukkan data: ", e)
        except Exception as e:
            print("Terjadi kesalahan: ", e)

submit_button.on_click(insert_data)

display( nama_anggota_input, nik_input, ttl_input, alamat_input, nomor_telepon_input, submit_button)

Text(value='', description='Nama Anggota:')

IntText(value=0, description='NIK:')

DatePicker(value=None, description='TTL:')

Text(value='', description='Alamat:')

IntText(value=0, description='No Telepon:')

Button(button_style='success', description='Masukkan Data', style=ButtonStyle(), tooltip='Klik untuk memasukka…

Data anggota berhasil dimasukkan.

### Delete Anggota

In [ ]:
# Function to fetch IDs from the SQL table
def get_ids_anggota_from_db():
    connection = sqlite3.connect('perpustakaan.db')  # Ganti dengan nama file basis data Anda
    cursor = connection.cursor()

    cursor.execute("SELECT id_anggota FROM anggota;")  # Ganti 'id_anggota' dan 'anggota' dengan nama kolom dan tabel yang sesuai
    ids_anggota = cursor.fetchall()

    cursor.close()
    connection.close()

    return [str(id[0]) for id in ids_anggota]

# Membuat widget dropdown untuk memilih ID anggota
id_dropdown_anggota = widgets.Dropdown(
    options=get_ids_anggota_from_db(),
    description='ID Anggota yang akan dihapus:',
    disabled=False
)

# Membuat tombol untuk menghapus rekaman anggota yang dipilih
delete_button_anggota = widgets.Button(
    description='Hapus Data Anggota',
    disabled=False,
    button_style='danger',  # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Klik untuk menghapus',
    icon='trash'
)

# Fungsi untuk menangani penghapusan anggota
def delete_record_anggota(button):
    id_to_delete_anggota = id_dropdown_anggota.value
    if id_to_delete_anggota:
        connection = sqlite3.connect('perpustakaan.db')  # Ganti dengan nama file basis data Anda
        cursor = connection.cursor()

        cursor.execute("DELETE FROM anggota WHERE id_anggota = ?;", (id_to_delete_anggota,))  # Ganti 'id_anggota' dan 'anggota' dengan nama kolom dan tabel yang sesuai
        connection.commit()

        cursor.close()
        connection.close()

        # Perbarui opsi dropdown
        id_dropdown_anggota.options = get_ids_anggota_from_db()
        print(f"Data anggota dengan ID {id_to_delete_anggota} berhasil dihapus.")

# Menampilkan widget untuk menghapus anggota
display(id_dropdown_anggota, delete_button_anggota)

# Melampirkan handler acara ke tombol untuk menghapus anggota
delete_button_anggota.on_click(delete_record_anggota)

Dropdown(description='ID Anggota yang akan dihapus:', options=('AG1', 'AG2', 'AG3', 'AG4', 'AG5', 'AG8', 'ANGO…

Button(button_style='danger', description='Hapus Data Anggota', icon='trash', style=ButtonStyle(), tooltip='Kl…

Data anggota dengan ID ANGOT7 berhasil dihapus.

## Tabel Buku ID

### Melihat Tabel

In [ ]:
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM buku;")
data1 = cursor.fetchall()
cursor.execute(f"PRAGMA table_info(buku);")
data102 = cursor.fetchall()
data102 = [item[1] for item in data102]

df = pd.DataFrame(data1, columns=data102)
df

,ID_Buku,judul,pengarang,penerbit,Tahun_terbit,klasifikasi
0,B1,Harry Potter dan Batu Bertuah,IDP1,PEN1,2005,KLS1
1,B2,Rahasia Alam Semesta,IDP2,PEN2,2010,KLS2
2,B3,Tesis Mengenai Manajemen Pendidikan,IDP3,PEN3,2022,KLS3
3,B4,Makalah Keamanan Siber,IDP4,PEN4,2018,KLS4
4,B5,Kumpulan Puisi Cinta,IDP5,PEN5,2014,KLS1
5,B6,Panduan Lengkap SEO,IDP6,PEN6,2019,KLS2
6,B7,Petualangan Sherina,IDP7,PEN7,2017,KLS1
7,B8,Jurnal Teknik Elektro Vol. 3,IDP8,PEN8,2020,KLS5
8,B9,Analisis Data Mining pada E-commerce,IDP9,PEN9,2021,KLS6
9,B10,Manajemen Pendidikan di Era Globalisasi,IDP3,PEN10,2022,KLS3

### Input Buku ID

In [ ]:
# Membuat widget input untuk data buku
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()
cursor.execute("SELECT DISTINCT id_pengarang FROM pengarang;")
data1 = cursor.fetchall()
cursor.execute("SELECT DISTINCT id_penerbit FROM penerbit;")
data2 = cursor.fetchall()
cursor.execute("SELECT DISTINCT id_klasifikasi FROM klasifikasi;")
data3 = cursor.fetchall()

listpengarang = [item[0] for item in data1]
listpenerbit = [item[0] for item in data2]
listklasifikasi = [item[0] for item in data3]


id_buku_input = widgets.Text(
    placeholder="Input ID BUku unique",
    value='',
    description='ID Buku:',
    disabled=False)

judul_input = widgets.Text(
    value='',
    description='Judul:',
    disabled=False)

pengarang_input = widgets.Dropdown(
    options=listpengarang,
    description='Pengarang:',
    disabled=False)

penerbit_input = widgets.Dropdown(
     options=listpenerbit,
    description='Penerbit:',
    disabled=False)

tahun_terbit_input = widgets.IntText(
    value=2023,
    description='Tahun Terbit:',
    disabled=False)

klasifikasi_input = widgets.Dropdown(
    options=listklasifikasi,
    description='Klasifikasi:',
    disabled=False)

submit_button = widgets.Button(
    description='Masukkan Data',
    disabled=False,
    button_style='success',
    tooltip='Klik untuk memasukkan data buku')


def generate_next_id():
    global counter_buku
    counter_buku +=1

    # Menghasilkan ID dengan format "KLS" diikuti dengan nomor
    next_id_with_format = f"B{counter_buku}"

    return next_id_with_format


def insert_data_buku(b):
    with sqlite3.connect('perpustakaan.db') as conn:
        c = conn.cursor()
        c.execute('PRAGMA foreign_keys = ON')
        try:
            # Memasukkan data buku
            next_id = generate_next_id()
            c.execute('''
                INSERT INTO buku (id_buku, judul, pengarang, penerbit, tahun_terbit, klasifikasi)
                VALUES (?, ?, ?, ?, ?, ?)
                ''',
                (next_id,
                judul_input.value,
                pengarang_input.value,
                penerbit_input.value,
                tahun_terbit_input.value,
                klasifikasi_input.value))
            print("Data buku berhasil dimasukkan.")
        except sqlite3.IntegrityError as e:
            print("Gagal memasukkan data: ", e)
        except Exception as e:
            print("Terjadi kesalahan: ", e)

submit_button.on_click(insert_data_buku)

display(judul_input, pengarang_input, penerbit_input, tahun_terbit_input, klasifikasi_input, submit_button)

Text(value='', description='Judul:')

Dropdown(description='Pengarang:', options=('IDP1', 'IDP2', 'IDP3', 'IDP4', 'IDP5', 'IDP6', 'IDP7', 'IDP8', 'I…

Dropdown(description='Penerbit:', options=('PEN1', 'PEN10', 'PEN2', 'PEN3', 'PEN4', 'PEN5', 'PEN6', 'PEN7', 'P…

IntText(value=2023, description='Tahun Terbit:')

Dropdown(description='Klasifikasi:', options=('KLS1', 'KLS2', 'KLS3', 'KLS4', 'KLS5', 'KLS6'), value='KLS1')

Button(button_style='success', description='Masukkan Data', style=ButtonStyle(), tooltip='Klik untuk memasukka…

Data buku berhasil dimasukkan.

### Delete Buku ID

In [ ]:
# Function to fetch IDs from the SQL table
def get_ids_from_db():
    connection = sqlite3.connect('perpustakaan.db')  # Ganti dengan nama file basis data Anda
    cursor = connection.cursor()

    cursor.execute("SELECT id_buku FROM buku;")  # Ganti 'id_buku' dan 'buku' dengan nama kolom dan tabel yang sesuai
    ids = cursor.fetchall()

    cursor.close()
    connection.close()

    return [str(id[0]) for id in ids]

# Membuat widget dropdown untuk memilih ID
id_dropdown = widgets.Dropdown(
    options=get_ids_from_db(),
    description='ID Buku yang akan dihapus:',
    disabled=False
)

# Membuat tombol untuk menghapus rekaman yang dipilih
delete_button = widgets.Button(
    description='Hapus Buku ID',
    disabled=False,
    button_style='danger',  # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Klik untuk menghapus',
    icon='trash'
)

# Fungsi untuk menangani penghapusan
def delete_record(button):
    id_to_delete = id_dropdown.value
    if id_to_delete:
        connection = sqlite3.connect('perpustakaan.db')  # Ganti dengan nama file basis data Anda
        cursor = connection.cursor()

        cursor.execute("DELETE FROM buku WHERE id_buku = ?;", (id_to_delete,))  # Ganti 'id_buku' dan 'buku' dengan nama kolom dan tabel yang sesuai
        connection.commit()

        cursor.close()
        connection.close()

        # Perbarui opsi dropdown
        id_dropdown.options = get_ids_from_db()
        print(f"Data dengan ID {id_to_delete} berhasil dihapus.")

# Menampilkan widget
display(id_dropdown, delete_button)

# Melampirkan handler acara ke tombol
delete_button.on_click(delete_record)

Dropdown(description='ID Buku yang akan dihapus:', options=('B1', 'B10', 'B11', 'B2', 'B3', 'B4', 'B5', 'B6', …

Button(button_style='danger', description='Hapus Buku ID', icon='trash', style=ButtonStyle(), tooltip='Klik un…

Data dengan ID B11 berhasil dihapus.

## Tabel Buku Per Copy

### Melihat Tabel

In [ ]:
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM buku_per_copy;")
data1 = cursor.fetchall()
cursor.execute(f"PRAGMA table_info(buku_per_copy);")
data102 = cursor.fetchall()
data102 = [item[1] for item in data102]

df = pd.DataFrame(data1, columns=data102)
df

   id_buku_per_copy Id_buku  tersedia
0               BK1      B9         1
1               BK2      B9         1
2               BK3      B7         1
3               BK4      B8         1
4               BK5      B3         1
5               BK6      B6         1
6               BK7      B7         1
7               BK8      B2         1
8               BK9      B6         1
9              BK11      B1         1
10             BK12      B8         1
11             BK13      B2         1
12             BK14      B8         1
13             BK15      B1         1
14             BK16     B10         1
15             BK17      B9         1
16             BK18      B9         1
17             BK19      B6         1
18             BK20      B9         1
19             BK21      B1         1
20             BK22      B5         1
21             BK23      B8         1
22             BK24      B8         1
23             BK25      B4         1
24             BK26      B1         1
25             BK27      B7         1
26             BK28      B8         1
27             BK29      B2         1
28             BK30      B3         1
29             BK31      B8         1
30             BK32      B2         1
31             BK33      B9         1
32             BK34      B8         1
33             BK35      B5         1
34             BK36      B3         1
35             BK37      B6         1
36             BK38      B1         1
37             BK39      B5         1
38             BK40      B9         1
39             BK41      B1         1
40             BK42      B5         1
41             BK43      B8         1
42             BK44      B3         1
43             BK45      B6         1
44             BK46      B9         1
45             BK47      B3         1
46             BK48      B4         1
47             BK49      B6         1
48             BK50      B5         1
49             BK51      B9         1
50             BK52      B7         1
51             BK53      B3         1
52             BK55     B10         1

### Input Buku Per Copy

In [ ]:
import sqlite3
from ipywidgets import widgets
from IPython.display import display

# Membuat koneksi dan cursor ke database
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()

# Mengambil data id_buku untuk dropdown
cursor.execute("SELECT DISTINCT id_buku FROM buku;")
data1 = cursor.fetchall()

listbuku = [item[0] for item in data1]

# Membuat widget input untuk data buku_per_copy
id_buku_input = widgets.Dropdown(
    options=listbuku,
    description='ID Buku:',
    disabled=False)

submit_button = widgets.Button(
    description='Masukkan Data',
    disabled=False,
    button_style='success',
    tooltip='Klik untuk memasukkan data buku')


def generate_next_id():
    global counter_bukucopy
    counter_bukucopy +=1

    # Menghasilkan ID dengan format "KLS" diikuti dengan nomor
    next_id_with_format = f"BK{counter_bukucopy}"

    return next_id_with_format

def insert_data_buku_per_copy(b):
    with sqlite3.connect('perpustakaan.db') as conn:
        c = conn.cursor()
        c.execute('PRAGMA foreign_keys = ON')
        try:
          nextid = generate_next_id()
          c.execute('''
              INSERT INTO buku_per_copy (id_buku_per_copy, id_buku, tersedia)
              VALUES (?, ?, ?)
              ''',
              (nextid,
              id_buku_input.value,
              1))
          print("Data buku per copy berhasil dimasukkan.")
        except sqlite3.IntegrityError as e:
            print("Gagal memasukkan data: ", e)
        except Exception as e:
            print("Terjadi kesalahan: ", e)

submit_button.on_click(insert_data_buku_per_copy)

display(id_buku_input, submit_button)

Dropdown(description='ID Buku:', options=('B1', 'B10', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B9'), value=…

Button(button_style='success', description='Masukkan Data', style=ButtonStyle(), tooltip='Klik untuk memasukka…

Data buku per copy berhasil dimasukkan.
Data buku per copy berhasil dimasukkan.

### Delete Buku Per copy

In [ ]:
# Function to fetch IDs from the SQL table
def get_ids_buku_per_copy_from_db():
    connection = sqlite3.connect('perpustakaan.db')  # Ganti dengan nama file basis data Anda
    cursor = connection.cursor()

    cursor.execute("SELECT id_buku_per_copy FROM buku_per_copy;")  # Ganti 'id_buku_per_copy' dan 'buku_per_copy' dengan nama kolom dan tabel yang sesuai
    ids_buku_per_copy = cursor.fetchall()

    cursor.close()
    connection.close()

    return [str(id[0]) for id in ids_buku_per_copy]

# Membuat widget dropdown untuk memilih ID buku per copy
id_dropdown_buku_per_copy = widgets.Dropdown(
    options=get_ids_buku_per_copy_from_db(),
    description='ID Buku Per Copy yang akan dihapus:',
    disabled=False
)

# Membuat tombol untuk menghapus rekaman buku per copy yang dipilih
delete_button_buku_per_copy = widgets.Button(
    description='Hapus Data Buku Per Copy',
    disabled=False,
    button_style='danger',  # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Klik untuk menghapus',
    icon='trash'
)

# Fungsi untuk menangani penghapusan buku per copy
def delete_record_buku_per_copy(button):
    id_to_delete_buku_per_copy = id_dropdown_buku_per_copy.value
    if id_to_delete_buku_per_copy:
        connection = sqlite3.connect('perpustakaan.db')  # Ganti dengan nama file basis data Anda
        cursor = connection.cursor()

        cursor.execute("DELETE FROM buku_per_copy WHERE id_buku_per_copy = ?;", (id_to_delete_buku_per_copy,))  # Ganti 'id_buku_per_copy' dan 'buku_per_copy' dengan nama kolom dan tabel yang sesuai
        connection.commit()

        cursor.close()
        connection.close()

        # Perbarui opsi dropdown
        id_dropdown_buku_per_copy.options = get_ids_buku_per_copy_from_db()
        print(f"Data buku per copy dengan ID {id_to_delete_buku_per_copy} berhasil dihapus.")

# Menampilkan widget untuk menghapus buku per copy
display(id_dropdown_buku_per_copy, delete_button_buku_per_copy)

# Melampirkan handler acara ke tombol untuk menghapus buku per copy
delete_button_buku_per_copy.on_click(delete_record_buku_per_copy)

Dropdown(description='ID Buku Per Copy yang akan dihapus:', options=('BK1', 'BK10', 'BK11', 'BK12', 'BK13', 'B…

Button(button_style='danger', description='Hapus Data Buku Per Copy', icon='trash', style=ButtonStyle(), toolt…

Data buku per copy dengan ID BK10 berhasil dihapus.
Data buku per copy dengan ID BK54 berhasil dihapus.

## Tabel Pengarang

### Melihat Tabel

In [ ]:
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM pengarang;")
data1 = cursor.fetchall()
cursor.execute(f"PRAGMA table_info(pengarang);")
data102 = cursor.fetchall()
data102 = [item[1] for item in data102]

df = pd.DataFrame(data1, columns=data102)
df

,id_pengarang,nama_pengarang,email_pengarang,tempat_tinggal
0,IDP1,J.K. Rowling,jkrowling@gmail.com,Green Road 21
1,IDP2,Stephen Hawking,stephenhw@gmail.com,Saint Major Road 17
2,IDP3,Andi Wijaya,andiwjy@gmail.com,Jalan Mawar No 14
3,IDP4,Siti Aisyah,sitiaisyah@gmail.com,Perumahan Sabar Cluster Halo
4,IDP5,Chairil Anwar,chairilanwar@gmail.com,Jalan Anugerah No 8
5,IDP6,Andi Pratama,andipratama@gmail.com,Apartment Kedoya No 8A
6,IDP7,Ria Tanasya,riatanasya@gmail.com,Perumahan Merdeka II
7,IDP8,Universitas Gadjah Mada,ugm@gmail.com,"Bulaksumur, Yogyakarta"
8,IDP9,Budi Santoso,budisantoso@gmail.com,Apartment Ayodya

### Input Pengarang

In [ ]:
import sqlite3
from ipywidgets import widgets
from IPython.display import display

# Membuat koneksi dan cursor ke database
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()

# Membuat widget input untuk data pengarang

nama_pengarang_input = widgets.Text(
    value='',
    description='Nama Pengarang:',
    disabled=False)

email_input = widgets.Text(
    value='',
    description='Email:',
    disabled=False)

tempat_tinggal_input = widgets.Text(
    value='',
    description='Tempat Tinggal:',
    disabled=False)

submit_button = widgets.Button(
    description='Masukkan Data',
    disabled=False,
    button_style='success',
    tooltip='Klik untuk memasukkan data pengarang')

def generate_next_id():
    global counter_pengarang
    counter_pengarang +=1

    # Menghasilkan ID dengan format "KLS" diikuti dengan nomor
    next_id_with_format = f"IDP{counter_pengarang}"

    return next_id_with_format


def insert_data_pengarang(b):
    with sqlite3.connect('perpustakaan.db') as conn:
        c = conn.cursor()
        c.execute('PRAGMA foreign_keys = ON')
        try:
            # Memasukkan data pengarang
            nextid = generate_next_id()
            c.execute('''
                INSERT INTO pengarang (id_pengarang, nama_pengarang, email_pengarang, tempat_tinggal)
                VALUES (?, ?, ?, ?)
                ''',
                (nextid,
                nama_pengarang_input.value,
                email_input.value,
                tempat_tinggal_input.value))
            print("Data pengarang berhasil dimasukkan.")
        except sqlite3.IntegrityError as e:
            print("Gagal memasukkan data: ", e)
        except Exception as e:
            print("Terjadi kesalahan: ", e)

submit_button.on_click(insert_data_pengarang)

display(nama_pengarang_input, email_input, tempat_tinggal_input, submit_button)

Text(value='', description='Nama Pengarang:')

Text(value='', description='Email:')

Text(value='', description='Tempat Tinggal:')

Button(button_style='success', description='Masukkan Data', style=ButtonStyle(), tooltip='Klik untuk memasukka…

### Delete Pengarang

In [ ]:
# Function to fetch IDs from the SQL table
def get_ids_pengarang_from_db():
    connection = sqlite3.connect('perpustakaan.db')  # Ganti dengan nama file basis data Anda
    cursor = connection.cursor()

    cursor.execute("SELECT id_pengarang FROM pengarang;")  # Ganti 'id_pengarang' dan 'pengarang' dengan nama kolom dan tabel yang sesuai
    ids_pengarang = cursor.fetchall()

    cursor.close()
    connection.close()

    return [str(id[0]) for id in ids_pengarang]

# Membuat widget dropdown untuk memilih ID pengarang
id_dropdown_pengarang = widgets.Dropdown(
    options=get_ids_pengarang_from_db(),
    description='ID Pengarang yang akan dihapus:',
    disabled=False
)

# Membuat tombol untuk menghapus rekaman pengarang yang dipilih
delete_button_pengarang = widgets.Button(
    description='Hapus Data Pengarang',
    disabled=False,
    button_style='danger',  # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Klik untuk menghapus',
    icon='trash'
)

# Fungsi untuk menangani penghapusan pengarang
def delete_record_pengarang(button):
    id_to_delete_pengarang = id_dropdown_pengarang.value
    if id_to_delete_pengarang:
        connection = sqlite3.connect('perpustakaan.db')  # Ganti dengan nama file basis data Anda
        cursor = connection.cursor()

        cursor.execute("DELETE FROM pengarang WHERE id_pengarang = ?;", (id_to_delete_pengarang,))  # Ganti 'id_pengarang' dan 'pengarang' dengan nama kolom dan tabel yang sesuai
        connection.commit()

        cursor.close()
        connection.close()

        # Perbarui opsi dropdown
        id_dropdown_pengarang.options = get_ids_pengarang_from_db()
        print(f"Data pengarang dengan ID {id_to_delete_pengarang} berhasil dihapus.")

# Menampilkan widget untuk menghapus pengarang
display(id_dropdown_pengarang, delete_button_pengarang)

# Melampirkan handler acara ke tombol untuk menghapus pengarang
delete_button_pengarang.on_click(delete_record_pengarang)

Dropdown(description='ID Pengarang yang akan dihapus:', options=('IDP1', 'IDP2', 'IDP3', 'IDP4', 'IDP5', 'IDP6…

Button(button_style='danger', description='Hapus Data Pengarang', icon='trash', style=ButtonStyle(), tooltip='…

## Tabel Penerbit

### Melihat Tabel

In [ ]:
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM penerbit;")
data1 = cursor.fetchall()
cursor.execute(f"PRAGMA table_info(penerbit);")
data102 = cursor.fetchall()
data102 = [item[1] for item in data102]

df = pd.DataFrame(data1, columns=data102)
df

  id_penerbit               nama_penerbit      telepon          email_penerbit
0        PEN1            Gramedia Pustaka  81234567890      gramedia@gmail.com
1        PEN2             Bentang Pustaka  87765432109      bpustaka@gmail.com
2        PEN3      Universitas Hasanuddin  85678901234         unhas@gmail.com
3        PEN4      Universitas Padjajaran  89943215678         unpad@gmail.com
4        PEN5               Balai Pustaka  82187650987  balaipustaka@gmail.com
5        PEN6       Elex Media Komputindo  83890123456          elex@gmail.com
6        PEN7                       Mizan  88123456789         mizan@gmail.com
7        PEN8                   UGM Press  81789012345      ugmpress@gmail.com
8        PEN9  Institut Teknologi Bandung  82345678901               itb@ac.id
9       PEN10      Universitas Hasanuddin  87654321098             unhas@ac.id

### Input Penerbit

In [ ]:
import sqlite3
from ipywidgets import widgets
from IPython.display import display

# Membuat koneksi dan cursor ke database
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()

# Membuat widget input untuk data penerbit

nama_penerbit_input = widgets.Text(
    value='',
    description='Nama Penerbit:',
    disabled=False)

telp_penerbit_input = widgets.Text(
    value='',
    description='Telp Penerbit:',
    disabled=False)

email_penerbit_input = widgets.Text(
    value='',
    description='Email:',
    disabled=False)

submit_button = widgets.Button(
    description='Masukkan Data',
    disabled=False,
    button_style='success',
    tooltip='Klik untuk memasukkan data penerbit')


def generate_next_id():
    global counter_penerbit
    counter_penerbit +=1

    # Menghasilkan ID dengan format "KLS" diikuti dengan nomor
    next_id_with_format = f"PEN{counter_penerbit}"

    return next_id_with_format

def insert_data_penerbit(b):
    with sqlite3.connect('perpustakaan.db') as conn:
        c = conn.cursor()
        c.execute('PRAGMA foreign_keys = ON')
        try:
            # Memasukkan data penerbit
            nextid = generate_next_id()
            c.execute('''
                INSERT INTO penerbit (id_penerbit, nama_penerbit, telepon, email_penerbit)
                VALUES (?, ?, ?, ?)
                ''',
                (nextid,
                nama_penerbit_input.value,
                telp_penerbit_input.value,
                email_penerbit_input.value))
            print("Data penerbit berhasil dimasukkan.")
        except sqlite3.IntegrityError as e:
            print("Gagal memasukkan data: ", e)
        except Exception as e:
            print("Terjadi kesalahan: ", e)

submit_button.on_click(insert_data_penerbit)

display(nama_penerbit_input, telp_penerbit_input, email_penerbit_input, submit_button)

Text(value='', description='Nama Penerbit:')

Text(value='', description='Telp Penerbit:')

Text(value='', description='Email:')

Button(button_style='success', description='Masukkan Data', style=ButtonStyle(), tooltip='Klik untuk memasukka…

### Delete Penerbit

In [ ]:
# Function to fetch IDs from the SQL table
def get_ids_penerbit_from_db():
    connection = sqlite3.connect('perpustakaan.db')  # Ganti dengan nama file basis data Anda
    cursor = connection.cursor()

    cursor.execute("SELECT id_penerbit FROM penerbit;")  # Ganti 'id_penerbit' dan 'penerbit' dengan nama kolom dan tabel yang sesuai
    ids_penerbit = cursor.fetchall()

    cursor.close()
    connection.close()

    return [str(id[0]) for id in ids_penerbit]

# Membuat widget dropdown untuk memilih ID penerbit
id_dropdown_penerbit = widgets.Dropdown(
    options=get_ids_penerbit_from_db(),
    description='ID Penerbit yang akan dihapus:',
    disabled=False
)

# Membuat tombol untuk menghapus rekaman penerbit yang dipilih
delete_button_penerbit = widgets.Button(
    description='Hapus Data Penerbit',
    disabled=False,
    button_style='danger',  # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Klik untuk menghapus',
    icon='trash'
)

# Fungsi untuk menangani penghapusan penerbit
def delete_record_penerbit(button):
    id_to_delete_penerbit = id_dropdown_penerbit.value
    if id_to_delete_penerbit:
        connection = sqlite3.connect('perpustakaan.db')  # Ganti dengan nama file basis data Anda
        cursor = connection.cursor()

        cursor.execute("DELETE FROM penerbit WHERE id_penerbit = ?;", (id_to_delete_penerbit,))  # Ganti 'id_penerbit' dan 'penerbit' dengan nama kolom dan tabel yang sesuai
        connection.commit()

        cursor.close()
        connection.close()

        # Perbarui opsi dropdown
        id_dropdown_penerbit.options = get_ids_penerbit_from_db()
        print(f"Data penerbit dengan ID {id_to_delete_penerbit} berhasil dihapus.")

# Menampilkan widget untuk menghapus penerbit
display(id_dropdown_penerbit, delete_button_penerbit)

# Melampirkan handler acara ke tombol untuk menghapus penerbit
delete_button_penerbit.on_click(delete_record_penerbit)

Dropdown(description='ID Penerbit yang akan dihapus:', options=('PEN1', 'PEN10', 'PEN2', 'PEN3', 'PEN4', 'PEN5…

Button(button_style='danger', description='Hapus Data Penerbit', icon='trash', style=ButtonStyle(), tooltip='K…

## Tabel Klasifikasi

### Melihat Tabel

In [ ]:
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM klasifikasi;")
data1 = cursor.fetchall()
cursor.execute(f"PRAGMA table_info(klasifikasi);")
data102 = cursor.fetchall()
data102 = [item[1] for item in data102]

df = pd.DataFrame(data1, columns=data102)
df

  id_klasifikasi    klasifikasi
0           KLS1     Buku Fiksi
1           KLS2  Buku Nonfiksi
2           KLS3          Tesis
3           KLS4        Makalah
4           KLS5         Jurnal
5           KLS6        Skripsi

### Input Klasifikasi

In [ ]:
import sqlite3
from ipywidgets import widgets
from IPython.display import display

# Membuat koneksi dan cursor ke database
conn = sqlite3.connect('perpustakaan.db')
cursor = conn.cursor()

# Membuat widget input untuk data klasifikasi

klasifikasi_input = widgets.Text(
    value='',
    description='Klasifikasi:',
    disabled=False)

submit_button = widgets.Button(
    description='Masukkan Data',
    disabled=False,
    button_style='success',
    tooltip='Klik untuk memasukkan data klasifikasi')

def generate_next_id():
    global counter_klasifikasi
    counter_klasifikasi +=1

    # Menghasilkan ID dengan format "KLS" diikuti dengan nomor
    next_id_with_format = f"KLS{counter_klasifikasi}"

    return next_id_with_format
def insert_data_klasifikasi(b):
    with sqlite3.connect('perpustakaan.db') as conn:
        c = conn.cursor()
        c.execute('PRAGMA foreign_keys = ON')
        try:
            # Memasukkan data klasifikasi
            newid = generate_next_id()
            c.execute('''
                INSERT INTO klasifikasi (id_klasifikasi, klasifikasi)
                VALUES (?, ?)
                ''',
                (newid,
                klasifikasi_input.value))
            print("Data klasifikasi berhasil dimasukkan.")
        except sqlite3.IntegrityError as e:
            print("Gagal memasukkan data: ", e)
        except Exception as e:
            print("Terjadi kesalahan: ", e)

submit_button.on_click(insert_data_klasifikasi)

display( klasifikasi_input, submit_button)

Text(value='', description='Klasifikasi:')

Button(button_style='success', description='Masukkan Data', style=ButtonStyle(), tooltip='Klik untuk memasukka…

### Delete Klasifikasi

In [ ]:
# Function to fetch IDs from the SQL table
def get_ids_klasifikasi_from_db():
    connection = sqlite3.connect('perpustakaan.db')  # Ganti dengan nama file basis data Anda
    cursor = connection.cursor()

    cursor.execute("SELECT id_klasifikasi FROM klasifikasi;")  # Ganti 'id_klasifikasi' dan 'klasifikasi' dengan nama kolom dan tabel yang sesuai
    ids_klasifikasi = cursor.fetchall()

    cursor.close()
    connection.close()

    return [str(id[0]) for id in ids_klasifikasi]

# Membuat widget dropdown untuk memilih ID klasifikasi
id_dropdown_klasifikasi = widgets.Dropdown(
    options=get_ids_klasifikasi_from_db(),
    description='ID Klasifikasi yang akan dihapus:',
    disabled=False
)

# Membuat tombol untuk menghapus rekaman klasifikasi yang dipilih
delete_button_klasifikasi = widgets.Button(
    description='Hapus Data Klasifikasi',
    disabled=False,
    button_style='danger',  # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Klik untuk menghapus',
    icon='trash'
)

# Fungsi untuk menangani penghapusan klasifikasi
def delete_record_klasifikasi(button):
    id_to_delete_klasifikasi = id_dropdown_klasifikasi.value
    if id_to_delete_klasifikasi:
        connection = sqlite3.connect('perpustakaan.db')  # Ganti dengan nama file basis data Anda
        cursor = connection.cursor()

        cursor.execute("DELETE FROM klasifikasi WHERE id_klasifikasi = ?;", (id_to_delete_klasifikasi,))  # Ganti 'id_klasifikasi' dan 'klasifikasi' dengan nama kolom dan tabel yang sesuai
        connection.commit()

        cursor.close()
        connection.close()

        # Perbarui opsi dropdown
        id_dropdown_klasifikasi.options = get_ids_klasifikasi_from_db()
        print(f"Data klasifikasi dengan ID {id_to_delete_klasifikasi} berhasil dihapus.")

# Menampilkan widget untuk menghapus klasifikasi
display(id_dropdown_klasifikasi, delete_button_klasifikasi)

# Melampirkan handler acara ke tombol untuk menghapus klasifikasi
delete_button_klasifikasi.on_click(delete_record_klasifikasi)

Dropdown(description='ID Klasifikasi yang akan dihapus:', options=('KLS1', 'KLS2', 'KLS3', 'KLS4', 'KLS5', 'KL…

Button(button_style='danger', description='Hapus Data Klasifikasi', icon='trash', style=ButtonStyle(), tooltip…

# POV Anggota

## Ingin Melihat ketersediaan Buku

In [ ]:
import ipywidgets as widgets
from IPython.display import display, clear_output
import sqlite3
from datetime import datetime

# Create search input widget
search_input = widgets.Text(
    value='',
    placeholder='Masukkan kata kunci pencarian',
    description='Cari Buku:',
    style={'description_width': 'initial'},
    disabled=False
)

# Create a button to initiate the search
search_button = widgets.Button(
    description='Cari',
    button_style='primary',
    tooltip='Klik untuk mencari buku berdasarkan kata kunci'
)

# Create an output widget to display search results
output_search_results = widgets.Output()

# Create an output widget to display book availability
output_info_buku = widgets.Output()

# Function to search for books based on the keyword
def search_books(b):
    with output_search_results:
        clear_output()
        keyword = search_input.value

        # Connect to the database
        conn = sqlite3.connect('perpustakaan.db')
        c = conn.cursor()

        # Perform a search query to include the author's name
        c.execute('''
            SELECT b.judul, p.nama_pengarang
            FROM buku b
            JOIN pengarang p ON b.pengarang = p.id_pengarang
            WHERE b.judul LIKE ? OR p.nama_pengarang LIKE ?
        ''', ('%' + keyword + '%', '%' + keyword + '%'))
        results = c.fetchall()

        conn.close()

        if results:
            listjudul = [f"{item[0]} oleh {item[1]}" for item in results]
            id_buku_widget.options = listjudul
            print(f"Ditemukan {len(results)} buku:")
            for judul in listjudul:
                print(f"- {judul}")
        else:
            print("Tidak ditemukan buku dengan kata kunci tersebut.")

# Create a dropdown widget for selecting a book title
id_buku_widget = widgets.Dropdown(
    options=[],
    description='Judul Buku:',
    style={'description_width': 'initial'}
)

# Create a button to check the availability of the selected book
cek_ketersediaan_button = widgets.Button(
    description='Cek Ketersediaan',
    button_style='warning',
    tooltip='Cek ketersediaan buku berdasarkan judul'
)

# Function to check the availability of the selected book
def cek_info_buku(b):
    with output_info_buku:
        clear_output()
        judul_buku = id_buku_widget.value

        if not judul_buku:
            print("Silakan pilih judul buku terlebih dahulu.")
            return

        # Extract the actual book title from the selected option
        judul_buku_actual = judul_buku.split(' oleh ')[0]

        conn = sqlite3.connect('perpustakaan.db')
        c = conn.cursor()

        # Query to get book information and availability including the author's name
        c.execute('''
            SELECT b.judul, p.nama_pengarang, b.id_buku, COUNT(bpc.id_buku_per_copy) AS total_copy,
                   COUNT(CASE WHEN bpc.tersedia = 1 THEN 1 END) AS banyak_tersedia,
                   GROUP_CONCAT(CASE WHEN bpc.tersedia = 1 THEN bpc.id_buku_per_copy END) AS available_copies
            FROM buku b
            JOIN pengarang p ON b.pengarang = p.id_pengarang
            LEFT JOIN buku_per_copy bpc ON b.id_buku = bpc.id_buku
            WHERE b.judul = ?
            GROUP BY b.judul, p.nama_pengarang, b.id_buku
        ''', (judul_buku_actual,))
        info_buku = c.fetchone()

        conn.close()

        if info_buku:
            judul, pengarang, id_buku, total_copy, banyak_tersedia, available_copies = info_buku
            available_copies = available_copies if available_copies else "Tidak ada salinan yang tersedia"
            print(f"Judul: {judul}\nPenulis: {pengarang}\nID Buku: {id_buku}\nTotal Salinan: {total_copy}\nTersedia: {banyak_tersedia}\nID Buku Per Copy Tersedia: {available_copies}")
        else:
            print("Buku dengan judul tersebut tidak ditemukan.")

# Bind the search button to the search function
search_button.on_click(search_books)

# Bind the check availability button to the check function
cek_ketersediaan_button.on_click(cek_info_buku)

# Display the search input, search button, dropdown for selecting book title, check availability button, and output widgets
display(search_input, search_button, output_search_results, id_buku_widget, cek_ketersediaan_button, output_info_buku)

Text(value='', description='Cari Buku:', placeholder='Masukkan kata kunci pencarian', style=DescriptionStyle(d…

Button(button_style='primary', description='Cari', style=ButtonStyle(), tooltip='Klik untuk mencari buku berda…

Output()

Dropdown(description='Judul Buku:', options=(), style=DescriptionStyle(description_width='initial'), value=Non…

Button(button_style='warning', description='Cek Ketersediaan', style=ButtonStyle(), tooltip='Cek ketersediaan …

Output()